router, ctx, example: add session support
nedpals/vex pull request #52
Opened 2022-04-01 18:42 UTC by islonely

Added support for sessions. Supports both local storage, MySQL databases, and custom storage options. Also created an example.

2022-04-01 20:20 UTC, BenStigsen commented
Support for cookies is very nice, but perhaps it would be better to have a database independent networking module. To be able to extract the data and store it if wanted. Adding MySQL and SQLite as a dependency to Vex does not seem so fitting.

2022-04-01 20:29 UTC, islonely commented
That's a good point. I didn't even think about dependencies. I could make the default storage method a local json file similar to how the `SqliteStore` works but without the need to have Sqlite installed. There wasn't any particular reason I chose to use Sqlite. It just seemed like an easy option to work with.

2022-04-03 02:42 UTC, nedpals requested changes
You should rebase this first to master before I can merge this. Also, it would be cool if all or most of the session-related code be relocated to a separate module (that is, if structs in `ctx` don't rely on sessions)

2022-04-03 02:42 UTC, nedpals commented on ctx/ctx.v
> +	cookies   map[string]Cookie
Cookies weren't automatically added to the request context to make processing light as much as possible and parse it on demand if needed. Better yet call `parse_cookies` inside `start_session` instead.

2022-04-03 02:42 UTC, nedpals commented on router/router.v
> +	req.cookies = req.parse_cookies() or { map[string]ctx.Cookie }
Again, we try to make request processing as light as possible so this should be removed.

2022-04-03 13:27 UTC, islonely commented
Yep, these are all good ideas. I'll have the changes made Soon™️

2022-04-03 22:39 UTC, islonely commented
> You should rebase this first to master before I can merge this. Also, it would be cool if all or most of the session-related code be relocated to a separate module (that is, if structs in `ctx` don't rely on sessions)

`git rebase master` says that the session-support branch is up to date :l
I believe everything else mentioned thus far has been resolved. Unless I totally overlooked something, which is very possible.

2022-04-03 22:41 UTC, islonely commented on ctx/ctx.v
> +	cookies   map[string]Cookie
This has been fixed. `parse_cookies` is now invoked in the start session function.

2022-04-04 00:00 UTC, nedpals commented
@islonely Try pulling master again since what I see here is that some of the code reverts the changes done by the latest commit.

2022-04-04 02:30 UTC, islonely commented
> ...what I see here is that some of the code reverts the changes done by the latest commit.

Yeah, I see the same on my end. I don't know why it did that. Anyways, I get "Already up to date" when using `git pull`. I'm gonna add you as a collaborator on my fork of vex on GitHub if you wanna go ahead and try to rebase. If all else fails, I can manually add back the code that was reverted in another commit.

2022-04-12 18:48 UTC, islonely commented
I could never get the rebase to work right, so I've just manually reverted the changes in a commit. If you go to the file changes tab on this page it should only show the changes I've made.

2022-04-15 07:24 UTC, nedpals approved these changes
I manually just cherry-picked the changes from the master. LGTM!

2022-04-15 07:58 UTC, merged