all: run `fmt -w .` to prevent warning msgs
nedpals/vex pull request #67
Opened 2023-11-26 16:39 UTC by dnkdev

format all files, to get rid of V's warnings (attribute new syntax)

2023-11-28 03:07 UTC, nedpals requested changes
I suggest that the formatting specific to import statements that I have commented be removed.

2023-11-28 03:07 UTC, nedpals commented on ctx/ctx.v
> +import nedpals.vex.utils
I'm not into V that much anymore but was this the proper way to import relative modules now? This might break setups where the `vex` folder is only used without having my username as the parent folder. (eg. import them as `vex` or some other name)

2023-11-28 03:07 UTC, nedpals commented on picoserver/server.v
> +import nedpals.vex.server { Router }
Same comment with previous.

2023-11-28 03:07 UTC, nedpals commented on router/router.v
> +import nedpals.vex.utils
Same comment with previous.

2023-11-28 03:07 UTC, nedpals commented on router/router_test.v
> +import nedpals.vex.ctx
Same comment with previous.

2023-11-28 03:07 UTC, nedpals commented on server/server.v
> +import nedpals.vex.utils
Same comment with previous.

2023-11-28 03:07 UTC, nedpals commented on session/session.v
> +import nedpals.vex.utils
Same comment with previous.

2023-11-28 03:07 UTC, nedpals commented on session/session.v
> +import nedpals.vex.ctx
Same comment with previous.

2023-11-28 03:07 UTC, nedpals commented on utils/utils.v
> +import nedpals.vex.mime
Same comment with previous.

2023-11-28 07:25 UTC, dnkdev commented
You absolutely right, problems could appear if path to module is changed. It is my recklessness. :) Should be ok now.

2023-12-04 09:52 UTC, nedpals submitted a review, later dismissed
Nice. Had to bump the version in your branch since the formatting will break previous language version

2023-12-04 11:19 UTC, dnkdev commented
So the #69 is here now, and I decided put #68 picoserver changes also here, it affects a picoserver example, which should compile altogether. I made a VEX 0.3.6, just forgot to pull before make changes, thats why force push.

2023-12-04 12:28 UTC, nedpals commented
Tests are green now. LGTM!

2023-12-04 12:29 UTC, merged